### ISSUE TITLE
Error on running the activity

### ISSUE THREAD

**Issue by yell0wfl4sh** [sugarlabs/mancala-activity#5] opened 2018-01-08 22:17 UTC
Activity shuts down abruptly and displays this error:
```
libpng error: bad adaptive filter value
Peter says: Can't find data/top.png
```

I think, file ```top.png``` is corrupt. Also, there is no way to fix it until we recover the image.

**Comment by quozl** [comment] 2018-01-08 22:46
Fixed in 31435c4 by extracting again from released bundle.

Yes, it was corrupt.  Looks like it was corrupted between activities.sugarlabs.org download and the commits by Tony Anderson.

You might like to check for other corruptions; as we don't know how it happened.

**Comment by quozl** [comment] 2018-01-08 23:30
I've done a recursive binary diff and no other unexplained corruptions are present.

**Closed as completed by quozl** 2018-01-08 23:30 UTC

**Comment by yell0wfl4sh** [comment] 2018-01-08 23:39
I guess ```top.png``` file got changed to a corrupted one in commit a5b4de985caff68777487f6b630b508570159a29 by mistake. It is working fine now.

I would also like to know how did you used recursive binary diff to find corrupted files. :)

**Comment by quozl** [comment] 2018-01-08 23:53
Initially, I used `meld`, then I used `diff -r` to confirm.  Reproducing that now for illustration;

```
$ git checkout abd5925d94756e513c6b0b9b1023f7e4842af85b  # before the fix
$ diff -ur ../mancala-22/Mancala.activity .
diff -ur ../mancala-22/Mancala.activity/activity/activity.info ./activity/activity.info
--- ../mancala-22/Mancala.activity/activity/activity.info       2011-04-30 18:54:52.000000000 +1000
+++ ./activity/activity.info    2018-01-09 09:42:58.289864994 +1100
@@ -6,3 +6,4 @@
 icon = activity
 show_launcher = yes
 exec = sugar-activity activity.PeterActivity
+repository = https://github.com/sugarlabs/mancala-activity.git
Binary files ../mancala-22/Mancala.activity/data/top.png and ./data/top.png differ
Only in .: .git
Only in .: LICENSE
$ git checkout master
$ █
```

For each change identified; assess cause.

**Comment by yell0wfl4sh** [comment] 2018-01-09 00:16
@quozl okay! Thanks :)
